# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 01:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beacon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('key', models.BinaryField()),
                ('reg_time', models.DateTimeField()),
                ('reg_counter', models.IntegerField()),
                ('k', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.CharField(max_length=16)),
                ('clock', models.IntegerField()),
                ('beacon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eddystone_resolver.Beacon')),
            ],
        ),
    ]
