# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eddystone_resolver', '0002_auto_20170619_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beacon',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='eid',
            name='eid',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
